# Clock signal
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# Reset and Power buttons
set_property PACKAGE_PIN P15 [get_ports rst_n_raw]
set_property PACKAGE_PIN R15 [get_ports power_btn_raw]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n_raw]
set_property IOSTANDARD LVCMOS33 [get_ports power_btn_raw]

# Control buttons
set_property PACKAGE_PIN P5 [get_ports menu_btn]
set_property PACKAGE_PIN V1 [get_ports level1_btn_raw]
set_property PACKAGE_PIN R11 [get_ports level2_btn_raw]
set_property PACKAGE_PIN U4 [get_ports level3_btn_raw]
set_property PACKAGE_PIN R17 [get_ports self_clean_btn_raw]
set_property IOSTANDARD LVCMOS33 [get_ports menu_btn]
set_property IOSTANDARD LVCMOS33 [get_ports level1_btn_raw]
set_property IOSTANDARD LVCMOS33 [get_ports level2_btn_raw]
set_property IOSTANDARD LVCMOS33 [get_ports level3_btn_raw]
set_property IOSTANDARD LVCMOS33 [get_ports self_clean_btn_raw]

# Switches and controls
set_property PACKAGE_PIN R1 [get_ports power_left_right_control]
set_property PACKAGE_PIN R2 [get_ports increase_gesture_time]
set_property PACKAGE_PIN T3 [get_ports query_gesture_time]
set_property PACKAGE_PIN M4 [get_ports hour_increment]
set_property PACKAGE_PIN N4 [get_ports minute_increment]
set_property PACKAGE_PIN T5 [get_ports query_upper_accumulated_time_switch]
set_property PACKAGE_PIN P2 [get_ports upper_hour_increase_switch]
set_property PACKAGE_PIN P3 [get_ports manual_reset_btn]
set_property PACKAGE_PIN U2 [get_ports lighting_switch]
set_property PACKAGE_PIN V2 [get_ports query_accumulated_time_switch]

set_property IOSTANDARD LVCMOS33 [get_ports power_left_right_control]
set_property IOSTANDARD LVCMOS33 [get_ports increase_gesture_time]
set_property IOSTANDARD LVCMOS33 [get_ports query_gesture_time]
set_property IOSTANDARD LVCMOS33 [get_ports hour_increment]
set_property IOSTANDARD LVCMOS33 [get_ports minute_increment]
set_property IOSTANDARD LVCMOS33 [get_ports query_upper_accumulated_time_switch]
set_property IOSTANDARD LVCMOS33 [get_ports upper_hour_increase_switch]
set_property IOSTANDARD LVCMOS33 [get_ports manual_reset_btn]
set_property IOSTANDARD LVCMOS33 [get_ports lighting_switch]
set_property IOSTANDARD LVCMOS33 [get_ports query_accumulated_time_switch]

# LED outputs
set_property PACKAGE_PIN H4 [get_ports lighting_state]
set_property PACKAGE_PIN G4 [get_ports {extraction_level[0]}]
set_property PACKAGE_PIN F6 [get_ports {extraction_level[1]}]
set_property PACKAGE_PIN K2 [get_ports {current_mode[0]}]
set_property PACKAGE_PIN J2 [get_ports {current_mode[1]}]
set_property PACKAGE_PIN J3 [get_ports {current_mode[2]}]
set_property PACKAGE_PIN J4 [get_ports cleaning_active]
set_property PACKAGE_PIN G3 [get_ports reminder_led]
set_property PACKAGE_PIN H5 [get_ports {query_gesture_time_value[0]}]
set_property PACKAGE_PIN H6 [get_ports {query_gesture_time_value[1]}]
set_property PACKAGE_PIN K1 [get_ports {query_gesture_time_value[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports lighting_state]
set_property IOSTANDARD LVCMOS33 [get_ports {extraction_level[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {extraction_level[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports cleaning_active]
set_property IOSTANDARD LVCMOS33 [get_ports reminder_led]
set_property IOSTANDARD LVCMOS33 [get_ports {query_gesture_time_value[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {query_gesture_time_value[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {query_gesture_time_value[2]}]

# Query LEDs
set_property PACKAGE_PIN J5 [get_ports {query_leds[4]}]
set_property PACKAGE_PIN K6 [get_ports {query_leds[3]}]
set_property PACKAGE_PIN L1 [get_ports {query_leds[2]}]
set_property PACKAGE_PIN M1 [get_ports {query_leds[1]}]
set_property PACKAGE_PIN K3 [get_ports {query_leds[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {query_leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {query_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {query_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {query_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {query_leds[0]}]

# Seven segment display enables
set_property PACKAGE_PIN G2 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN H1 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN G1 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN F1 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN E1 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN G6 [get_ports {seg_en[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]

# Seven segment display outputs - Left
set_property PACKAGE_PIN B4 [get_ports {seg_out0[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_out0[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_out0[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_out0[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_out0[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_out0[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_out0[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_out0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[0]}]

# Seven segment display outputs - Right
set_property PACKAGE_PIN D4 [get_ports {seg_out1[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_out1[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_out1[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_out1[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_out1[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_out1[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_out1[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_out1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[0]}]